name: Build metrics

on:
  schedule:
  - cron: '0 */1 * * *'
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  publish:
    name: generate repo metrics
    runs-on: ubuntu-latest
    steps:
      - name: Get the sources
        uses: actions/checkout@v2
      - name: Metrics contributors
        uses: lowlighter/metrics@latest
        with:
          template: repository
          base: ""
          committer_branch: gh-pages
          filename: metrics.repository.svg
          token: ${{ secrets.METRICS_TOKEN_WITH_SCOPES }}
          user: magicblock-labs
          repo: Solana.Unity-SDK
          plugin_contributors: yes
          plugin_contributors_contributions: yes
      - name: Stargazers, Watchers
        uses: lowlighter/metrics@latest
        with:
          template: repository
          base: ""
          committer_branch: gh-pages
          filename: people.repository.svg
          token: ${{ secrets.METRICS_TOKEN_WITH_SCOPES }}
          user: magicblock-labs
          repo: Solana.Unity-SDK
          plugin_people: yes
          plugin_people_types: stargazers, watchers
